import type { INodeTypeDescription } from '../../shared/types/N8n';
import { NODE_DISPLAY_NAME, NODE_NAME } from './InvoiceSender.constants';

const operationDisplay = (operations: string[]) => ({ show: { operation: operations } });

export const description: INodeTypeDescription = {
  displayName: NODE_DISPLAY_NAME,
  name: NODE_NAME,
  group: ['transform'],
  version: 2,
  description: 'Create and send invoices through a credential-backed provider REST API.',
  defaults: { name: NODE_DISPLAY_NAME },
  inputs: ['main'],
  outputs: ['main'],
  credentials: [{ name: 'invoiceRouterApi', required: true }],
  properties: [
    {
      displayName: 'Operation',
      name: 'operation',
      type: 'options',
      default: 'createAndSend',
      options: [
        { name: 'Create and Send Invoice', value: 'createAndSend' },
        { name: 'Create Invoice', value: 'create' },
        { name: 'Send Existing Invoice', value: 'send' },
        { name: 'Custom API Request', value: 'custom' },
      ],
    },
    {
      displayName: 'Provider Source',
      name: 'providerSource',
      type: 'options',
      default: 'input',
      options: [
        { name: 'Input Item', value: 'input' },
        { name: 'Manual', value: 'manual' },
      ],
    },
    {
      displayName: 'Provider ID',
      name: 'provider',
      type: 'string',
      default: 'custom',
      displayOptions: { show: { providerSource: ['manual'] } },
    },
    {
      displayName: 'Dry Run',
      name: 'dryRun',
      type: 'boolean',
      default: true,
      description: 'Build and return sanitized request plans without calling the provider. Disable after testing.',
    },
    {
      displayName: 'Create Endpoint',
      name: 'createEndpoint',
      type: 'string',
      default: '/invoices',
      description: 'Relative endpoint. Supports {requestId}, {provider}, and invoice field placeholders.',
      displayOptions: operationDisplay(['create', 'createAndSend']),
    },
    {
      displayName: 'Create Method',
      name: 'createMethod',
      type: 'options',
      default: 'POST',
      options: [
        { name: 'POST', value: 'POST' },
        { name: 'PUT', value: 'PUT' },
        { name: 'PATCH', value: 'PATCH' },
      ],
      displayOptions: operationDisplay(['create', 'createAndSend']),
    },
    {
      displayName: 'Create Body',
      name: 'createBodyMode',
      type: 'options',
      default: 'invoice',
      options: [
        { name: 'Normalized Invoice', value: 'invoice' },
        { name: 'Raw JSON', value: 'raw' },
      ],
      displayOptions: operationDisplay(['create', 'createAndSend']),
    },
    {
      displayName: 'Create Body JSON',
      name: 'createBodyJson',
      type: 'json',
      default: '{}',
      displayOptions: { show: { operation: ['create', 'createAndSend'], createBodyMode: ['raw'] } },
    },
    {
      displayName: 'Send Endpoint',
      name: 'sendEndpoint',
      type: 'string',
      default: '/invoices/{invoiceId}/send',
      description: 'Relative endpoint. {invoiceId} is replaced from the create response or input item.',
      displayOptions: operationDisplay(['send', 'createAndSend']),
    },
    {
      displayName: 'Send Method',
      name: 'sendMethod',
      type: 'options',
      default: 'POST',
      options: [
        { name: 'POST', value: 'POST' },
        { name: 'PUT', value: 'PUT' },
        { name: 'PATCH', value: 'PATCH' },
      ],
      displayOptions: operationDisplay(['send', 'createAndSend']),
    },
    {
      displayName: 'Send Body JSON',
      name: 'sendBodyJson',
      type: 'json',
      default: '{}',
      displayOptions: operationDisplay(['send', 'createAndSend']),
    },
    {
      displayName: 'Existing Invoice ID Field',
      name: 'existingInvoiceIdField',
      type: 'string',
      default: 'invoice_id',
      displayOptions: operationDisplay(['send']),
    },
    {
      displayName: 'Custom Endpoint',
      name: 'customEndpoint',
      type: 'string',
      default: '/',
      displayOptions: operationDisplay(['custom']),
    },
    {
      displayName: 'Custom Method',
      name: 'customMethod',
      type: 'options',
      default: 'POST',
      options: [
        { name: 'GET', value: 'GET' },
        { name: 'POST', value: 'POST' },
        { name: 'PUT', value: 'PUT' },
        { name: 'PATCH', value: 'PATCH' },
        { name: 'DELETE', value: 'DELETE' },
      ],
      displayOptions: operationDisplay(['custom']),
    },
    {
      displayName: 'Custom Body JSON',
      name: 'customBodyJson',
      type: 'json',
      default: '{}',
      displayOptions: operationDisplay(['custom']),
    },
    {
      displayName: 'Extra Headers JSON',
      name: 'extraHeadersJson',
      type: 'json',
      default: '{}',
      description: 'Per-node non-secret headers. Authentication remains in n8n credentials.',
    },
    {
      displayName: 'Query Parameters JSON',
      name: 'queryJson',
      type: 'json',
      default: '{}',
    },
    {
      displayName: 'Idempotency Header',
      name: 'idempotencyHeader',
      type: 'string',
      default: 'Idempotency-Key',
      description: 'Set blank to disable. The normalized invoice requestId is used as the value.',
    },
    {
      displayName: 'Invoice ID Response Path',
      name: 'invoiceIdPath',
      type: 'string',
      default: 'id',
      description: 'Dot path in the create/custom response, for example data.invoice.id.',
    },
    {
      displayName: 'Status Response Path',
      name: 'statusPath',
      type: 'string',
      default: 'status',
    },
    {
      displayName: 'Invoice URL Response Path',
      name: 'invoiceUrlPath',
      type: 'string',
      default: 'hosted_invoice_url',
    },
    {
      displayName: 'PDF URL Response Path',
      name: 'pdfUrlPath',
      type: 'string',
      default: 'invoice_pdf',
    },
    {
      displayName: 'Message Response Path',
      name: 'messagePath',
      type: 'string',
      default: 'message',
    },
    {
      displayName: 'Include Raw Response',
      name: 'includeRawResponse',
      type: 'boolean',
      default: false,
      description: 'Include provider response data in node output. Credentials are never included.',
    },
  ],
};
